"use client";
import { useState, useTransition } from "react";
import Image from "next/image";
import aboutMeData from "../constants/aboutmeData";
import TabButton from "./TabButton";
import ABOUT_ME_IMG from "../../../public/images/AboutMe2.jpg";

const AboutMeSection = () => {
	const [tab, setTab] = useState("skills");
	const [isPending, startTransition] = useTransition();

	const handleTabChange = (id) => {
		startTransition(() => {
			setTab(id);
		});
	};

	return (
		<section className="text-white" id="about">
			<div className="md:grid md:grid-cols-2 gap-8 items-start py-8 px-4 xl:gap-16 sm:py-16 xl:px-16">
				<Image
					src={ABOUT_ME_IMG}
					priority
					alt="programmer generated by AI"
					width={400}
					height={400}
					className="rounded-lg border border-[#33353F]"
				/>
				<div className="mt-4 md:mt-0 text-justify flex flex-col">
					<h2 className="text-4xl font-bold mb-4">About Me</h2>
					<p className="text-base md:text-lg">
						Hi, I am Wojtek - frontend developer with aspiration to fullstack
						programmer from Poland. I am currently in the process of learning
						the React framework. <br />
						<br />
						In addition to the frontend, I am also familiar with the workings of
						the backend. I have spent a lot of time to expand my knowledge of
						backend technologies such as Django, Databases and Django Rest
						Framework.
					</p>

					<div className="flex flex-row justify-start mt-7">
						<TabButton
							selectTab={() => handleTabChange("skills")}
							active={tab === "skills"}>
							Skills
						</TabButton>
						<TabButton
							selectTab={() => handleTabChange("education")}
							active={tab === "education"}>
							Education
						</TabButton>
						<TabButton
							selectTab={() => handleTabChange("experience")}
							active={tab === "experience"}>
							Experience
						</TabButton>
					</div>
					<div className="mt-4">
						{aboutMeData.find((about) => about.id === tab).content}
					</div>
				</div>
			</div>
		</section>
	);
};
export default AboutMeSection;
